### ISSUE TITLE
Crashing when loading - 1.16.1

### ISSUE THREAD

**Issue by Phelms215** [Samuel-Martineau/Potions-HUD-Fabric#2]
Crashing with an error initialising mixin config potions_hud_fabric.mixins.json

Full Log: https://pastebin.com/bUGKin4p

```
Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config potions_hud_fabric.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.addConfiguration(FabricMixinBootstrap.java:44)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap$$Lambda$78/1150585542.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.fabricmc.loader.launch.common.FabricMixinBootstrap.init(FabricMixinBootstrap.java:83)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:133)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_11 could not be set. Level is not supported
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1454)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:494)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:463)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1093)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
```

**Comment by Samuel-Martineau** [comment]
Which Minecraft version are you playing on?
Which mods are you playing with?
Are you launching the game with MultiMC or the vanilla launcher?

Just give me as much detail as possible.

**P.S.:** Thanks for using Pastebin

**Comment by Phelms215** [comment]
Minecraft 1.16.1 on win 10 64.
Fabric, fabric API, optfabric/optifine, replaymod
Vanilla launcher

I can provide versions of the mod or other logs later if needed.

**Comment by Samuel-Martineau** [comment]
Could you try without optifine/optifabric? I only tested this mod with sodium and I know that Optifine breaks a lot of things. Btw, sodium gives way better performances, so you might want to check it out.
